server:
  port: 8070
spring:

  #模板
  thymeleaf:
    mode: HTML
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true

  #连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: ownDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

  #quartz配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sql-map-config.xml

#pageHelper 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#日志
logging:
  level:
    cn.lianhy: debug
  config: classpath:logback.xml